spring:
  datasource:
    url: jdbc:postgresql://w1.pcl.kr:8024/locallife
    username: locallife
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
